import 'package:flutter/material.dart';
import '../../models/document_category_model.dart';
import '../../models/document_type_model.dart';

const List<DocumentCategory> documentCategories = [
  DocumentCategory(
    label: 'Complaints & Notices',
    icon: Icons.campaign_outlined,
    types: [
      DocumentType(
        id: 'legal_notice',
        label: 'Legal Notice',
        description: 'Formal legal notice to opposite party before litigation',
        promptHint: 'Describe the dispute, amount involved, and relief sought',
        requiredFields: ['Sender', 'Recipient', 'Dispute Details', 'Relief Sought'],
      ),
      DocumentType(
        id: 'consumer_complaint',
        label: 'Consumer Complaint',
        description: 'Complaint to consumer forum or company',
        promptHint: 'Describe the product/service issue and what you want',
        requiredFields: ['Company Name', 'Product/Service', 'Issue', 'Relief'],
      ),
      DocumentType(
        id: 'police_complaint',
        label: 'Police Complaint',
        description: 'FIR or complaint letter to police',
        promptHint: 'Describe the incident with date, place, and persons involved',
        requiredFields: ['Incident Date', 'Incident Place', 'Accused Details', 'Description'],
      ),
      DocumentType(
        id: 'cease_desist',
        label: 'Cease & Desist',
        description: 'Demand someone stop a specific activity',
        promptHint: 'Describe the activity you want stopped and why',
        requiredFields: ['Recipient', 'Activity to Stop', 'Legal Basis'],
      ),
      DocumentType(
        id: 'demand_letter',
        label: 'Demand Letter',
        description: 'Formal demand for payment or action',
        promptHint: 'Describe what you are demanding and the basis',
        requiredFields: ['Recipient', 'Demand', 'Amount (if any)', 'Deadline'],
      ),
    ],
  ),
  DocumentCategory(
    label: 'Agreements & Contracts',
    icon: Icons.handshake_outlined,
    types: [
      DocumentType(
        id: 'rent_agreement',
        label: 'Rent Agreement',
        description: 'Residential or commercial rental agreement',
        promptHint: 'Property details, rent amount, duration, terms',
        requiredFields: ['Landlord', 'Tenant', 'Property Address', 'Rent', 'Duration'],
      ),
      DocumentType(
        id: 'service_agreement',
        label: 'Service Agreement',
        description: 'Contract between service provider and client',
        promptHint: 'Services to be provided, payment, timelines',
        requiredFields: ['Provider', 'Client', 'Services', 'Payment Terms'],
      ),
      DocumentType(
        id: 'nda',
        label: 'NDA / Confidentiality',
        description: 'Non-disclosure agreement between parties',
        promptHint: 'What information is confidential and duration of NDA',
        requiredFields: ['Party 1', 'Party 2', 'Confidential Information', 'Duration'],
      ),
      DocumentType(
        id: 'employment_contract',
        label: 'Employment Contract',
        description: 'Agreement between employer and employee',
        promptHint: 'Role, salary, benefits, notice period, terms',
        requiredFields: ['Employer', 'Employee', 'Role', 'Salary', 'Start Date'],
      ),
      DocumentType(
        id: 'freelance_contract',
        label: 'Freelance Contract',
        description: 'Contract for freelance or consulting work',
        promptHint: 'Project scope, deliverables, payment, IP ownership',
        requiredFields: ['Client', 'Freelancer', 'Project Scope', 'Payment'],
      ),
      DocumentType(
        id: 'sale_agreement',
        label: 'Sale Agreement',
        description: 'Agreement for sale of goods or property',
        promptHint: 'What is being sold, price, payment terms, delivery',
        requiredFields: ['Seller', 'Buyer', 'Item/Property', 'Price', 'Terms'],
      ),
      DocumentType(
        id: 'partnership_deed',
        label: 'Partnership Deed',
        description: 'Deed for business partnership',
        promptHint: 'Partners, capital contribution, profit sharing, roles',
        requiredFields: ['Partners', 'Business', 'Capital', 'Profit Sharing'],
      ),
      DocumentType(
        id: 'mou',
        label: 'MOU / Term Sheet',
        description: 'Memorandum of understanding between parties',
        promptHint: 'Purpose, key terms, obligations of each party',
        requiredFields: ['Party 1', 'Party 2', 'Purpose', 'Key Terms'],
      ),
    ],
  ),
  DocumentCategory(
    label: 'Affidavits & Declarations',
    icon: Icons.verified_outlined,
    types: [
      DocumentType(
        id: 'general_affidavit',
        label: 'General Affidavit',
        description: 'Sworn statement of facts',
        promptHint: 'Facts to be declared and purpose of affidavit',
        requiredFields: ['Deponent Name', 'Facts to Declare', 'Purpose'],
      ),
      DocumentType(
        id: 'address_proof_affidavit',
        label: 'Address Proof Affidavit',
        description: 'Affidavit declaring residential address',
        promptHint: 'Current address and reason for affidavit',
        requiredFields: ['Name', 'Address', 'Reason'],
      ),
      DocumentType(
        id: 'name_change_affidavit',
        label: 'Name Change Affidavit',
        description: 'Affidavit for legal name change',
        promptHint: 'Old name, new name, and reason for change',
        requiredFields: ['Old Name', 'New Name', 'Reason'],
      ),
      DocumentType(
        id: 'income_affidavit',
        label: 'Income Affidavit',
        description: 'Declaration of income and financial status',
        promptHint: 'Income details, sources, and purpose',
        requiredFields: ['Name', 'Income Details', 'Purpose'],
      ),
    ],
  ),
  DocumentCategory(
    label: 'Court & Legal Filings',
    icon: Icons.account_balance_outlined,
    types: [
      DocumentType(
        id: 'consumer_court_complaint',
        label: 'Consumer Court Complaint',
        description: 'Formal complaint for consumer forum filing',
        promptHint: 'Full details of dispute, evidence, and relief sought',
        requiredFields: ['Complainant', 'Opposite Party', 'Dispute', 'Relief'],
      ),
      DocumentType(
        id: 'vakalatnama',
        label: 'Vakalatnama',
        description: 'Authorization letter to appoint an advocate',
        promptHint: 'Case details and advocate information',
        requiredFields: ['Client Name', 'Advocate Name', 'Court', 'Case Details'],
      ),
      DocumentType(
        id: 'bail_application',
        label: 'Bail Application',
        description: 'Application for bail in criminal matter',
        promptHint: 'Accused details, charges, and grounds for bail',
        requiredFields: ['Accused', 'Charges', 'Grounds for Bail', 'Court'],
      ),
      DocumentType(
        id: 'appeal_letter',
        label: 'Appeal Letter',
        description: 'Appeal against a decision or order',
        promptHint: 'Original decision, grounds of appeal, relief sought',
        requiredFields: ['Appellant', 'Against Whom', 'Original Decision', 'Grounds'],
      ),
    ],
  ),
  DocumentCategory(
    label: 'Personal & Property',
    icon: Icons.home_outlined,
    types: [
      DocumentType(
        id: 'will',
        label: 'Will / Testament',
        description: 'Legal will for asset distribution',
        promptHint: 'Assets, beneficiaries, and specific wishes',
        requiredFields: ['Testator', 'Assets', 'Beneficiaries'],
      ),
      DocumentType(
        id: 'power_of_attorney',
        label: 'Power of Attorney',
        description: 'Authorize someone to act on your behalf',
        promptHint: 'What powers are granted and for what purpose',
        requiredFields: ['Principal', 'Agent', 'Powers Granted', 'Purpose'],
      ),
      DocumentType(
        id: 'gift_deed',
        label: 'Gift Deed',
        description: 'Legal transfer of property as gift',
        promptHint: 'Property details, donor, recipient',
        requiredFields: ['Donor', 'Recipient', 'Property Details'],
      ),
      DocumentType(
        id: 'relinquishment_deed',
        label: 'Relinquishment Deed',
        description: 'Give up rights in inherited property',
        promptHint: 'Property details, parties, rights being given up',
        requiredFields: ['Relinguisher', 'Recipient', 'Property', 'Share'],
      ),
    ],
  ),
  DocumentCategory(
    label: 'HR & Employment',
    icon: Icons.business_center_outlined,
    types: [
      DocumentType(
        id: 'resignation_letter',
        label: 'Resignation Letter',
        description: 'Formal resignation from employment',
        promptHint: 'Role, company, last working day, reason (optional)',
        requiredFields: ['Employee Name', 'Role', 'Company', 'Last Working Day'],
      ),
      DocumentType(
        id: 'termination_letter',
        label: 'Termination Letter',
        description: 'Letter terminating an employee',
        promptHint: 'Reason for termination, notice period, dues',
        requiredFields: ['Employee', 'Reason', 'Last Date', 'Settlement'],
      ),
      DocumentType(
        id: 'experience_letter',
        label: 'Experience Letter',
        description: 'Certificate of employment experience',
        promptHint: 'Employee details, role, tenure, performance',
        requiredFields: ['Employee', 'Role', 'From Date', 'To Date'],
      ),
      DocumentType(
        id: 'offer_letter',
        label: 'Offer Letter',
        description: 'Job offer letter to a candidate',
        promptHint: 'Role, CTC, joining date, terms',
        requiredFields: ['Candidate', 'Role', 'CTC', 'Joining Date'],
      ),
    ],
  ),
];
