name: Build and Deploy to Firebase
on:
  push:
    branches: [main]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'
      - run: flutter pub get
      - run: flutter analyze --fatal-infos
      - run: flutter test
      - run: flutter build web --release
      - name: Deploy Firebase Hosting
        uses: w9jds/firebase-action@v13.31.0
        with:
          args: deploy --only hosting --project juslegal-2196
        env:
          GCP_SA_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
